name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  package:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: MatteoH2O1999/setup-python@v1
        with:
          python-version: "3.7"
      - name: Check packages
        run: |
          python3.7 -m pip install atomicwrites==1.0.0 --index-url https://pypi.org/simple/
          python3.7 -m pip config set global.index-url "https://:2022-03-16T13:28:14.391Z@time-machines-pypi.sealsecurity.io/"
          python3.7 -m pip install --force-reinstall pip setuptools wheel twine rstcheck;
          python3.7 setup.py sdist bdist_wheel;
          rstcheck README.rst CHANGES.rst
          python3.7 -m twine check dist/*
      - uses: "actions/upload-artifact@v4"
        with:
          name: artifacts
          path: ./dist/*
  test:
    env:
      SETUPTOOLS_USE_DISTUTILS: stdlib
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [macos-12, windows-latest, ubuntu-20.04]
        experimental: [false]
        nox-session: ['']

    runs-on: ${{ matrix.os }}
    name: ${{ fromJson('{"macos-latest":"macOS","windows-latest":"Windows","ubuntu-20.04":"Ubuntu"}')[matrix.os] }} ${{ matrix.python-version }} ${{ matrix.nox-session}}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python - ${{ matrix.python-version }}
        uses: MatteoH2O1999/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set Up Python 3 to run nox
        if: matrix.python-version != '3.7'
        uses: MatteoH2O1999/setup-python@v1
        with:
          python-version: "3"

      - name: Install Dependencies
        run: |
          python -m pip install atomicwrites==1.0.0 --index-url https://pypi.org/simple/
          python -m pip config set global.index-url "https://:2022-03-16T13:28:14.391Z@time-machines-pypi.sealsecurity.io/"
          python -m pip install --upgrade pip setuptools nox

      - name: Run Tests
        run: ./ci/run_tests.sh
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
          NOX_SESSION: ${{ matrix.nox-session }}

      - name: Upload Coverage
        if: ${{ matrix.nox-session != 'unsupported_python2' }}
        uses: "actions/upload-artifact@v2"
        with:
          name: coverage-data
          path: ".coverage.*"
          if-no-files-found: error


  coverage:
    runs-on: "ubuntu-20.04"
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: "Use latest Python so it understands all syntax"
        uses: MatteoH2O1999/setup-python@v1
        with:
          python-version: "3.10"

      - name: "Install coverage"
        run: |
          python -m pip install atomicwrites==1.0.0 --index-url https://pypi.org/simple/
          python -m pip config set global.index-url "https://:2022-03-16T13:28:14.391Z@time-machines-pypi.sealsecurity.io/"
          python -m pip install --upgrade coverage

      - name: "Download coverage data"
        uses: actions/download-artifact@v2
        with:
          name: coverage-data

      - name: "Combine & check coverage"
        run: |
          python -m coverage combine
          python -m coverage html --skip-covered --skip-empty
          python -m coverage report --ignore-errors --show-missing --fail-under=100

      - name: "Upload report if check failed"
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: htmlcov
        if: ${{ failure() }}
